### ISSUE TITLE
Unable to run Gutenberg Admin

### ISSUE THREAD

**Issue by jedifunk** [pristas-peter/wp-graphql-gutenberg#8]
When I try to update all my posts to be ready for the plugin, I get the following error on the third posts.

`Failed to update post with id 1716. The response is not a valid JSON response.`

WP version: 5.2.3

**Comment by lelandf** [comment]
I'm running into a similar issue. I get a slightly different error message:

> Failed to update post with id 1113. Failed to update block types option.

Tried deactivating every other plugin and using the default TwentyTwenty theme to eliminate possibility of theme/plugin conflicts. Same error.

If I figure something out I'll come back and update.

**Comment by pristas-peter** [comment]
@lelandf your error should be on the php's side, try to check logs for error messages

@jedifunk your error should be logged in yours browser console

**Comment by lelandf** [comment]
Thanks for the response. I ended up removing the `$ret = ` stuff and called all the `update_option` and `update_post_meta` functions directly.

Not entirely sure why that would matter however I managed to get all the correct post meta values:

![Screen Shot 2019-12-05 at 3 00 20 PM](https://user-images.githubusercontent.com/4604636/70269251-04a63980-1770-11ea-95c9-ea3f6f7eca8c.png)

And option value:

![Screen Shot 2019-12-05 at 3 01 03 PM](https://user-images.githubusercontent.com/4604636/70269283-14be1900-1770-11ea-95c9-23126df4ca10.png)

...in the database.

**Comment by pristas-peter** [comment]
Fixed in  4bd4b68

**Comment by jedifunk** [comment]
@pristas-peter hi! so sorry for the long delay, i was diverted to another project.

I'm still having this issue. I've updated to WP 5.3, wp-graphql 0.5, and this plugin to 0.1.3.

It still hangs on post id 1716.

Here's a parsed down version of the browser console. Happy to send the full if needed.
`GET https://xxxxx.com/wp-json/wp/v2/media/1745?context=edit&_locale=user 500
GET https://xxxxx.com/wp-json/wp/v2/media/1740?context=edit&_locale=user 500
GET https://xxxxx.com/wp-json/wp/v2/media/1751?context=edit&_locale=user 500
GET https://xxxxx.com/wp-json/wp/v2/media/1742?context=edit&_locale=user 500
yo @ VM5758 edit-post.min.js:6
(anonymous) @ post.php?post=1716&action=edit&wpGraphqlGutenbergForceUpdate:314
VM5664 data.min.js:1 Uncaught (in promise) {code: "invalid_json", message: "The response is not a valid JSON response."}
VM5664 data.min.js:1 Uncaught (in promise) {code: "invalid_json", message: "The response is not a valid JSON response."}
VM5664 data.min.js:1 Uncaught (in promise) {code: "invalid_json", message: "The response is not a valid JSON response."}
VM5664 data.min.js:1 Uncaught (in promise) {code: "invalid_json", message: "The response is not a valid JSON response."}
VM5683 api-fetch.min.js:1 POST https://xxxxx.com/wp-json/wp/v2/posts/1716?_locale=user 500`

**Comment by jedifunk** [comment]
@pristas-peter still having this issue... can you reopen the ticket?

**Comment by jedifunk** [comment]
any movement on this?
