### ISSUE TITLE
Error with Gatsby V3

### ISSUE THREAD

**Issue by tiggeymone** [pristas-peter/wp-graphql-gutenberg#89]
Hello, thank you for this great plugin.

Unfortunately I can't make it work with Gatsby V3. The build phase just stops with this error:

`Interfaces with the `nodeInterface` extension must have a field `id` of type `ID!`. Check the type definition of `WpBlockEditorContentNode`.`

Deactivating Wp GraphQL Gutenberg Wordpress plugin the error disappears, but obviously I can't get the gutenberg blocks fields using GraphQL. Note that from the Wordpress graphiql client everythings works correctly, but Gatsby, using Wordpress source v5 (the Gatsby v3 updated version) just seems not to compile.

Is there any way to fix this issue? Thank you!

**Comment by anicioalexandre** [comment]
Any news about this error?

**Comment by brogr** [comment]
I'm running into the same issue and downgraded to Gatsby v2 to resolve it. 
It's also being tracked here:
https://github.com/gatsbyjs/gatsby/issues/29966
https://github.com/gatsbyjs/gatsby/issues/30232

**Comment by rodrigo-arias** [comment]
Hopefully it can be solved since it is difficult to migrate this plugin after you have an integration, however, I am somewhat skeptical because I have not seen the owner maintain the plugin or even answer the issues.

**Comment by brogr** [comment]
Does anyone have the capacity to test [this suggested solution](https://github.com/gatsbyjs/gatsby/issues/29966#issuecomment-808040261)?

**Comment by pristas-peter** [comment]
Hi everybody, to be honest I don't have much time for this plugin right now, but PRs are always welcome. However this seems like a minor bug, I'll see what I can do.

**Comment by pristas-peter** [comment]
Could you try this branch? 

https://github.com/pristas-peter/wp-graphql-gutenberg/tree/gatsby-v3-test

**Comment by rodrigo-arias** [comment]
@brogr that solution didn't work for me.

@pristas-peter thanks for working on this, I have a different error now
```
gatsby-source-wordpress  (undefined) location: line 1, column: 510
Field "id" of type "Block!" must have a sub selection.
Error path: undefined

**Comment by Albin-w** [comment]
Hi,

I have minor knowledge of php, so i don't know if this fix is the way to go - but it seems that i have got things working this evening with a tweak in the branch @pristas-peter commented. 

This seems to solve the error. After this i had to make sure all my other plugins where updated for any braking changes with gatsby v3 - https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/

Sorry for commenting with an image, I'm not familiar with what you can do with Github.


<img width="786" alt="Screenshot 2021-03-28 at 23 58 56" src="https://user-images.githubusercontent.com/74892160/112769516-c34f3280-9021-11eb-98df-729dcf2724bb.png">

**Comment by TylerBarnes** [comment]
For anyone who needs a workaround, you can add this to your plugin options:

```
{
  resolve: `gatsby-source-wordpress`,
  options: {
    type: {
      BlockEditorContentNode: { exclude: true }
    }
  }
}
```

I will have to add some logic that auto excludes node types that don't have an id or non_null id

**Comment by pristas-peter** [comment]
Fixed in e3827bb626ee82b694e4ca45e5a0c9476a835232

**Comment by rodrigo-arias** [comment]
At least for me this is not fixed. Maybe it needs an adjustment also in `gatsby-source-wordpress` as Tyler mentions.
Excluding the node prevents errors, but of course you are not fetching the Block data.

**Comment by pristas-peter** [comment]
```gatsby-source-wordpress  (undefined) location: line 1, column: 510
Field "id" of type "Block!" must have a sub selection.
Error path: undefined

Error occurred while fetching nodes of the "BlockEditorPreview" type.```

The error above seems like an issue with the source plugin.

@TylerBarnes
@rodrigo-arias

**Comment by dannyvaughton** [comment]
Nor me, I am now getting

```
gatsby-source-wordpress  (undefined) location: line 1, column: 510
         Field "id" of type "Block!" must have a sub selection.
```

**Comment by TylerBarnes** [comment]
I think that's not a source plugin issue as that error is happening while fetching from WPGraphQL, not on the Gatsby side. It looks like the error is saying the `id` field is typed as `Block!` (which would be an object type and require a sub-selection) but it should be typed as `ID!`, right?

**Comment by TylerBarnes** [comment]
This https://github.com/pristas-peter/wp-graphql-gutenberg/commit/e3827bb626ee82b694e4ca45e5a0c9476a835232#diff-657bdea0255816a3f6039d76e52f6021deb86dc513cb8d7f030726dd998254c9R17 should be `'type' => ['non_null' => 'ID']`  as far as I can tell.

**Comment by pristas-peter** [comment]
Hi, should be fixed in 39dec642e8eacd94e6f695edab03d39a845f9af6

**Comment by rodrigo-arias** [comment]
I had tried that before but it seems that I forgot update the blocks registry. I can confirm that this is fixed. Thanks @pristas-peter
